export const Type = {
	FETCH_POSTS_START: "fetch/FETCH_POSTS_START",
	FETCH_POSTS_SUCCESS: "fetch/FETCH_POSTS_SUCCESS",
	FETCH_POSTS_ERROR: "fetch/FETCH_POSTS_ERROR",
	REMOVE_CONTACT_START: "fetch/REMOVE_CONTACT_START",
	REMOVE_CONTACT_SUCCESS: "fetch/REMOVE_CONTACT_SUCCESS",
	REMOVE_CONTACT_ERROR: "fetch/REMOVE_CONTACT_ERROR",
	ADD_CONTACT: "type/ADD_CONTACT",
	REMOVE_CONTACT: "type/REMOVE_CONTACT",
	ADD_FILTER: "type/ADD_FILTER",
};
